import * as MUX from '@ritaj/mux'
import * as Storage from '@ritaj/storage'

import { Fault, Unhandled } from './fault.ts'

type Constructor<T> = new (...args: any[]) => T

// A per-instance id used to correlate an action with its echoed response. Unlike
// queries (matched by content hash so identical asks dedupe), each action issued
// is a distinct request, so identity is an explicit nonce.
function correlationId(): string {
  return (
    globalThis.crypto?.randomUUID?.() ??
    `${Date.now()}-${Math.random().toString(36).slice(2)}`
  )
}

export type DataStructure =
  | Record<PropertyKey, any>
  | Record<PropertyKey, any>[]
  | string
  | number
  | boolean
  | null
  | undefined

export interface Resolver<Q extends Query<DataStructure, any> = any> {
  Resolve(q: Q): Promise<Q extends Query<infer R, any> ? R : never>
}

/**
 * @todo Simplify types.
 */
export abstract class AsyncResolver<Q extends AsyncQuery<any, any> = any> implements Resolver<Query<AsyncResult<Q extends AsyncQuery<infer R, any> ? R : never>>> {
  abstract Submit(q: Q): Promise<string>
  abstract Execute(
    q: Q
  ): Promise<AsyncResult<Q extends AsyncQuery<infer R, any> ? R : never>>

  async Resolve(
    q: Q
  ): Promise<AsyncResult<Q extends AsyncQuery<infer R, any> ? R : never>> {
    
    if (!q.IsSubmitted) {
      const handle = await this.Submit(q)
      q.Submit(handle)

      return { status: AsyncStatus.Pending }
    }

    return await this.Execute(q)
  }
}

export interface Handler<A extends Action<any, any> = any> {
  Handle(a: A): Promise<A extends Action<infer R, any> ? R : never>
}

/**
 * What a query and a command have in common: either is answered, or ends
 * with a fault that travels back in its place.
 *
 * `F` names the app faults it may end with, for typing only — `Attempt`
 * makes the caller handle them. Nothing checks it at runtime: a resolver
 * may still throw any fault, and the caller still gets the protocol ones.
 */
/**
 * An answer as it travels: nested in the packet's JSON — never a JSON string
 * inside it — so something reading the packet without its classes (a guard
 * restricting what a caller may see) can address its fields. `{}` until it is
 * answered, so answering with `null` stays distinct from not being answered.
 */
type Answered<T> = { value?: T }

/**
 * What the answer will be on the other side of the wire: a JSON copy, so a
 * packet answered in-process (no transport serializing it) gives back the
 * same plain data, never the resolver's own objects (a `Date`, a class).
 */
function answered<T>(data: T): Answered<T> {
  return data === undefined ? {} : { value: JSON.parse(JSON.stringify(data)) }
}

export abstract class Message<R extends DataStructure = any, F extends Fault = never> extends MUX.Packet {
  private readonly fault = this.c.Object<Record<string, unknown>>({}, 'horizon.fault')

  /** Type-only: what this message is answered with. Never set. */
  declare readonly Answer?: R
  /** Type-only: the app faults this message declares. Never set. */
  declare readonly Faults?: F

  /** Ends this message with `fault` instead of an answer — for the receiving side, before it sends it back. */
  Fail(fault: Fault) {
    this.fault.Write(JSON.parse(fault.Serialized))
  }

  /** The fault it ended with, as the class it was thrown as. */
  get Fault(): Fault | undefined {
    const tree = this.fault.Read()
    return Object.keys(tree).length === 0 ? undefined : Fault.Load(JSON.stringify(tree))
  }
}

export class Query<out T extends DataStructure = any, F extends Fault = never> extends Message<T, F> {
  private readonly result: Storage.Primitive<Answered<unknown>> = this.c.Object<Answered<unknown>>({}, 'query.result')

  async Execute(r: Resolver<this>) {
    const d = await r.Resolve(this)
    return d as T
  }

  Wrap(data: T) {
    this.result.Write(answered(data))
  }

  get Result(): T | undefined {
    return this.result.Read().value as T | undefined
  }

  /**
   *  Check if this query is equal to another query by comparing their hashes
   *  and constructors.
   *
   *  The hash is generated by dumping the properties defined with codec
   *  excluding the `result` argument.
   *
   * @param other Another Query instance
   * @returns Whether the 2 query have the same hash and constructor
   */
  Is(other: Query<any, any>): boolean {
    return this.Hash === other.Hash && this.constructor === other.constructor
  }

  get Hash(): string {
    const sheet = Storage.Json.Empty()

    const args = this.c.Exclude('query.result').Exclude('horizon.fault')
    args.Dump(sheet)

    return sheet.Serialized
  }
}

export class Action<R extends DataStructure = undefined, F extends Fault = never> extends Message<R, F> {
  // Correlates the request with its echoed response; the constructor default is
  // overwritten by Restore when the packet arrives over the wire.
  private readonly nonce = this.c.String(correlationId(), 'action.nonce')
  private readonly result: Storage.Primitive<Answered<unknown>> = this.c.Object<Answered<unknown>>({}, 'action.result')

  async Execute(h: Handler<this>) {
    return (await h.Handle(this)) as R
  }

  Wrap(data: R) {
    this.result.Write(answered(data))
  }

  get Result(): R | undefined {
    return this.result.Read().value as R | undefined
  }

  get Nonce(): string {
    return this.nonce.Read()
  }

  /**
   * Actions are matched to their echoed response by nonce (each issue is a
   * distinct request), not by content hash the way queries are.
   */
  Is(other: Action<any, any>): boolean {
    return this.Nonce === other.Nonce && this.constructor === other.constructor
  }
}

export enum AsyncStatus {
  Pending = 'pending',
  Completed = 'completed',
  Failed = 'failed',
}

export type AsyncOptions = {
  timeout?: number
  interval?: number
}

export type AsyncResult<T extends DataStructure = any> = {
  status: AsyncStatus
  value?: T
}

/**
 * Async queries are a kind of queries that instead of being resolved immediately
 * and populate the `Result` property with the response of the query, they
 * are resolved asynchronously therefore initially the `Result` property is
 * `undefined`, the `Status` property can be used to check if the query is still
 * pending, completed or failed.
 *
 * When you `client.Ask` an `AsyncQuery`, it will return a promise that will be
 * resolved when the query is completed, and rejected if the query is failed or
 * still pending after the specified timeout.
 *
 */
export class AsyncQuery<T extends DataStructure = any, F extends Fault = never> extends Query<T, F> {
  private readonly status = this.c.String(
    AsyncStatus.Pending,
    'query.async.status'
  )
  private readonly handle = this.c.String('', 'query.async.handle')

  get Status() {
    return this.status.Read() as AsyncStatus
  }

  override Fail(fault?: Fault) {
    this.status.Write(AsyncStatus.Failed)
    if (fault) super.Fail(fault)
  }

  Complete(data: T) {
    this.status.Write(AsyncStatus.Completed)
    this.Wrap(data)
  }

  Submit(handle: string) {
    this.handle.Write(handle)
  }

  /**
   * Indicates whether the query has been submitted i.e. the query has been sent
   * to the executor and is being processed. In practice it means the `Handle`
   * property has been populated.
   */
  get IsSubmitted(): boolean {
    return this.handle.Read() !== ''
  }

  get Handle() {
    return this.handle.Read()
  }

  override get Hash(): string {
    const sheet = Storage.Json.Empty()

    const args = this.c
      .Exclude('query.result')
      .Exclude('query.async.status')
      .Exclude('query.async.handle')
      .Exclude('horizon.fault')

    args.Dump(sheet)

    return sheet.Serialized
  }

  static IsAsync(q: Query<any, any> | MUX.Packet): q is AsyncQuery<any, any> {
    return q instanceof AsyncQuery
  }

  /**
   *  Check if this query is equal to another query by comparing their hashes
   *  and constructors.
   *
   *  The hash is generated by dumping the properties defined with codec
   *  excluding the `result` argument and the `async.status` argument.
   *
   * @param other Another Query instance
   * @returns Whether the 2 query have the same hash and constructor
   */
  override Is(other: AsyncQuery<any, any> | Query<any, any>): boolean {
    return this.Hash === other.Hash && this.constructor === other.constructor
  }
}

MUX.Packet.Register(Query, '/horizon.query')
MUX.Packet.Register(AsyncQuery, '/horizon.async_query')
MUX.Packet.Register(Action, '/horizon.action')

export class Resolvers implements Resolver {
  constructor(
    readonly registry = new Map<Constructor<Query>, Resolver<Query>>()
  ) {}

  Use<Q extends Query>(q: Constructor<Q>, r: Resolver<Q>): this
  Use<Q extends AsyncQuery>(q: Constructor<Q>, r: AsyncResolver<Q>): this
  Use<T extends DataStructure>(
    q: Constructor<Query<T>>,
    r: Resolver<Query<T>>
  ): this {
    this.registry.set(q, r)
    return this
  }

  Resolve<T extends DataStructure>(q: Query<T>): Promise<T> {
    const resolver = this.registry.get(q.constructor as Constructor<Query<T>>)

    if (!resolver) {
      throw new Unhandled(`No resolver for ${MUX.Packet.Registry.Read(q)}`)
    }

    return resolver.Resolve(q)
  }
}

export class Handlers implements Handler {
  constructor(
    readonly registry = new Map<Constructor<Action<any, any>>, Handler>()
  ) {}

  Use<A extends Action<any, any>>(a: Constructor<A>, h: Handler<A>): this {
    this.registry.set(a, h)
    return this
  }

  Handle(a: Action): Promise<any> {
    const handler = this.registry.get(a.constructor as Constructor<Action<any, any>>)

    if (!handler) {
      throw new Unhandled(`No handler for ${MUX.Packet.Registry.Read(a)}`)
    }

    return handler.Handle(a)
  }
}
