import * as MUX from '@ritaj/mux'
import * as Storage from '@ritaj/storage'

type Constructor<T> = new (...args: any[]) => T

// A per-instance id used to correlate an action with its echoed response. Unlike
// queries (matched by content hash so identical asks dedupe), each action issued
// is a distinct request, so identity is an explicit nonce.
function correlationId(): string {
  return (
    globalThis.crypto?.randomUUID?.() ??
    `${Date.now()}-${Math.random().toString(36).slice(2)}`
  )
}

export type DataStructure =
  | Record<PropertyKey, any>
  | Record<PropertyKey, any>[]
  | string
  | number
  | boolean
  | null
  | undefined

export interface Resolver<Q extends Query<DataStructure> = any> {
  Resolve(q: Q): Promise<Q extends Query<infer R> ? R : never>
}

/**
 * @todo Simplify types.
 */
export abstract class AsyncResolver<Q extends AsyncQuery = any> implements Resolver<Query<AsyncResult<Q extends AsyncQuery<infer R> ? R : never>>> {
  abstract Submit(q: Q): Promise<string>
  abstract Execute(
    q: Q
  ): Promise<AsyncResult<Q extends AsyncQuery<infer R> ? R : never>>

  async Resolve(
    q: Q
  ): Promise<AsyncResult<Q extends AsyncQuery<infer R> ? R : never>> {
    
    if (!q.IsSubmitted) {
      const handle = await this.Submit(q)
      q.Submit(handle)

      return { status: AsyncStatus.Pending }
    }

    return await this.Execute(q)
  }
}

export interface Handler<A extends Action<any> = any> {
  Handle(a: A): Promise<A extends Action<infer R> ? R : never>
}

export class Query<T extends DataStructure = any> extends MUX.Packet {
  private readonly result = this.c.String('', 'query.result')

  async Execute(r: Resolver<this>) {
    const d = await r.Resolve(this)
    return d as T
  }

  Wrap(data: T) {
    this.result.Write(JSON.stringify(data))
  }

  get Result(): T | undefined {
    const raw = this.result.Read()

    if (raw == null || raw === '') {
      return undefined
    }

    const parsed = JSON.parse(raw)

    return parsed as T
  }

  /**
   *  Check if this query is equal to another query by comparing their hashes
   *  and constructors.
   *
   *  The hash is generated by dumping the properties defined with codec
   *  excluding the `result` argument.
   *
   * @param other Another Query instance
   * @returns Whether the 2 query have the same hash and constructor
   */
  Is(other: Query): boolean {
    return this.Hash === other.Hash && this.constructor === other.constructor
  }

  get Hash(): string {
    const sheet = Storage.Json.Empty()

    const args = this.c.Exclude('query.result')
    args.Dump(sheet)

    return sheet.Serialized
  }
}

export class Action<R extends DataStructure = undefined> extends MUX.Packet {
  // Correlates the request with its echoed response; the constructor default is
  // overwritten by Restore when the packet arrives over the wire.
  private readonly nonce = this.c.String(correlationId(), 'action.nonce')
  private readonly result = this.c.String('', 'action.result')

  async Execute(h: Handler<this>) {
    return (await h.Handle(this)) as R
  }

  Wrap(data: R) {
    if (data === undefined) return
    this.result.Write(JSON.stringify(data))
  }

  get Result(): R | undefined {
    const raw = this.result.Read()

    if (raw == null || raw === '') {
      return undefined
    }

    return JSON.parse(raw) as R
  }

  get Nonce(): string {
    return this.nonce.Read()
  }

  /**
   * Actions are matched to their echoed response by nonce (each issue is a
   * distinct request), not by content hash the way queries are.
   */
  Is(other: Action<any>): boolean {
    return this.Nonce === other.Nonce && this.constructor === other.constructor
  }
}

export enum AsyncStatus {
  Pending = 'pending',
  Completed = 'completed',
  Failed = 'failed',
}

export type AsyncOptions = {
  timeout?: number
  interval?: number
}

export type AsyncResult<T extends DataStructure = any> = {
  status: AsyncStatus
  value?: T
}

/**
 * Async queries are a kind of queries that instead of being resolved immediately
 * and populate the `Result` property with the response of the query, they
 * are resolved asynchronously therefore initially the `Result` property is
 * `undefined`, the `Status` property can be used to check if the query is still
 * pending, completed or failed.
 *
 * When you `client.Ask` an `AsyncQuery`, it will return a promise that will be
 * resolved when the query is completed, and rejected if the query is failed or
 * still pending after the specified timeout.
 *
 */
export class AsyncQuery<T extends DataStructure = any> extends Query<T> {
  private readonly status = this.c.String(
    AsyncStatus.Pending,
    'query.async.status'
  )
  private readonly handle = this.c.String('', 'query.async.handle')

  get Status() {
    return this.status.Read() as AsyncStatus
  }

  Fail() {
    this.status.Write(AsyncStatus.Failed)
  }

  Complete(data: T) {
    this.status.Write(AsyncStatus.Completed)
    this.Wrap(data)
  }

  Submit(handle: string) {
    this.handle.Write(handle)
  }

  /**
   * Indicates whether the query has been submitted i.e. the query has been sent
   * to the executor and is being processed. In practice it means the `Handle`
   * property has been populated.
   */
  get IsSubmitted(): boolean {
    return this.handle.Read() !== ''
  }

  get Handle() {
    return this.handle.Read()
  }

  get Hash(): string {
    const sheet = Storage.Json.Empty()

    const args = this.c
      .Exclude('query.result')
      .Exclude('query.async.status')
      .Exclude('query.async.handle')

    args.Dump(sheet)

    return sheet.Serialized
  }

  static IsAsync(q: Query | MUX.Packet): q is AsyncQuery {
    return q instanceof AsyncQuery
  }

  /**
   *  Check if this query is equal to another query by comparing their hashes
   *  and constructors.
   *
   *  The hash is generated by dumping the properties defined with codec
   *  excluding the `result` argument and the `async.status` argument.
   *
   * @param other Another Query instance
   * @returns Whether the 2 query have the same hash and constructor
   */
  Is(other: AsyncQuery | Query): boolean {
    return this.Hash === other.Hash && this.constructor === other.constructor
  }
}

MUX.Packet.Register(Query, '/horizon.query')
MUX.Packet.Register(AsyncQuery, '/horizon.async_query')
MUX.Packet.Register(Action, '/horizon.action')

export class Resolvers implements Resolver {
  constructor(
    readonly registry = new Map<Constructor<Query>, Resolver<Query>>()
  ) {}

  Use<Q extends Query>(q: Constructor<Q>, r: Resolver<Q>): this
  Use<Q extends AsyncQuery>(q: Constructor<Q>, r: AsyncResolver<Q>): this
  Use<T extends DataStructure>(
    q: Constructor<Query<T>>,
    r: Resolver<Query<T>>
  ): this {
    this.registry.set(q, r)
    return this
  }

  Resolve<T extends DataStructure>(q: Query<T>): Promise<T> {
    const resolver = this.registry.get(q.constructor as Constructor<Query<T>>)

    if (!resolver) {
      throw new Error(`No resolver found for query ${q.constructor.name}`)
    }

    return resolver.Resolve(q)
  }
}

export class Handlers implements Handler {
  constructor(
    readonly registry = new Map<Constructor<Action<any>>, Handler>()
  ) {}

  Use<A extends Action<any>>(a: Constructor<A>, h: Handler<A>): this {
    this.registry.set(a, h)
    return this
  }

  Handle(a: Action): Promise<any> {
    const handler = this.registry.get(a.constructor as Constructor<Action<any>>)

    if (!handler) {
      throw new Error(`No handler found for action ${a.constructor.name}`)
    }

    return handler.Handle(a)
  }
}
