import { isEnvRef, type ResolvedManifest, type SecretRef } from '@khatm/spec'

function literal(value: unknown): string {
  return JSON.stringify(value)
}

/**
 * `value` as code, written like JSON, except that a value the deployment
 * supplies is read from its environment, as Better Auth would be given it.
 * Recursive: the value is a tree.
 */
function placeable(value: unknown): string {
  if (isEnvRef(value)) return `Deno.env.get(${literal(value.env)})!`
  if (Array.isArray(value)) return `[${value.map(placeable).join(',')}]`
  if (typeof value !== 'object' || value === null) return literal(value)
  const entries = Object.entries(value).map(([key, entry]) =>
    `${literal(key)}:${placeable(entry)}`
  )
  return `{${entries.join(',')}}`
}

function secret(ref: SecretRef): string {
  return 'env' in ref
    ? `Deno.env.get(${literal(ref.env)})!`
    : `Deno.readTextFileSync(${literal(ref.file)}).replace(/\\n$/, '')`
}

/**
 * Plain Better Auth code equivalent to a resolved manifest, so anyone can
 * leave the orchestrator and embed Better Auth directly. Nothing here
 * imports khatm. Capabilities that need khatm's code stay as comments.
 */
export function ejectAuth(
  resolved: ResolvedManifest,
  header: { revision: string; manifest: string },
): string {
  const { auth } = resolved
  const database = auth.database
  const imports = new Set<string>(["import { betterAuth } from 'better-auth'"])
  const plugins = [
    ...auth.plugins.map((p) => ({ kind: p.kind, options: p.options })),
    ...Object.keys(resolved.derived).filter((p) => p.startsWith('plugins.'))
      .sort().map((path) => {
        const value = resolved.derived[path].value as {
          kind: string
          options: Record<string, unknown>
        }
        return { kind: value.kind, options: value.options }
      }),
  ]
  if (plugins.length > 0) {
    imports.add(
      `import { ${
        [...new Set(plugins.map((p) => p.kind))].sort().join(', ')
      } } from 'better-auth/plugins'`,
    )
  }

  let databaseCode: string
  switch (database.dialect) {
    case 'sqlite':
      imports.add("import { DatabaseSync } from 'node:sqlite'")
      databaseCode = `new DatabaseSync(${secret(database.url)})`
      break
    case 'postgres':
      imports.add("import pg from 'pg'")
      databaseCode = `new pg.Pool({
      connectionString: ${secret(database.url)},${
        database.schema === undefined
          ? ''
          : `\n      options: ${
            literal(`-c search_path=${database.schema},public`)
          },`
      }
    })`
      break
    default:
      databaseCode =
        `undefined /* TODO: pass a ${database.dialect} connection, this build of khatm cannot open one yet */`
  }

  // The newest version signs and verifies session cookies, so it goes first.
  const secrets = [...auth.secrets].sort((a, b) => b.version - a.version)
    .map((s) => `    { version: ${s.version}, value: ${secret(s.value)} },`)
    .join('\n')
  const social = Object.entries(auth.socialProviders).sort(([a], [b]) =>
    a.localeCompare(b)
  ).map(([id, c]) =>
    `    ${id}: { clientId: ${secret(c.clientId)}, clientSecret: ${
      secret(c.clientSecret)
    } },`
  ).join('\n')
  const origins = resolved.derived['trustedOrigins']?.value as
    | string[]
    | undefined
  const cookies = resolved.derived['advanced.crossSubDomainCookies']?.value

  const lines = [
    `baseURL: ${placeable(auth.baseURL)},`,
    `secrets: [\n${secrets}\n  ],`,
    `database: ${databaseCode},`,
  ]
  if (origins) lines.push(`trustedOrigins: ${placeable(origins)},`)
  if (auth.emailAndPassword) {
    lines.push(`emailAndPassword: {
    enabled: ${auth.emailAndPassword.enabled},
    requireEmailVerification: ${
      auth.emailAndPassword.requireVerification ?? false
    },
  },`)
  }
  if (social) lines.push(`socialProviders: {\n${social}\n  },`)
  if (plugins.length > 0) {
    lines.push(
      `plugins: [\n${
        plugins.map((p) =>
          `    ${p.kind}(${
            Object.keys(p.options).length === 0 ? '' : literal(p.options)
          }),`
        ).join('\n')
      }\n  ],`,
    )
  }
  if (cookies) {
    lines.push(`advanced: { crossSubDomainCookies: ${placeable(cookies)} },`)
  }
  if (auth.hooks.length > 0) {
    lines.push(
      `// khatm capabilities with no plain equivalent yet: ${
        auth.hooks.map((h) => h.name).join(', ')
      }`,
    )
  }

  return `// Generated by khatm from revision ${header.revision} (manifest ${header.manifest}).
// Plain Better Auth: no khatm code is needed to run it.
${[...imports].join('\n')}

export const auth = betterAuth({
  ${lines.join('\n  ')}
})
`
}
