// Not generated: the icon set this kit uses in place of Fluid's Lucide
// default, Untitled UI (which Fluid Functionalism prefers). vendor.py points
// icon-context.tsx at this map, so re-vendoring keeps it.
//
// Every role keeps its meaning; where Untitled UI has no glyph of that name
// the nearest one stands in (noted below). Its components take `size`,
// `strokeWidth` and `className`, the whole contract icon-context asks for.

import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell01,
  BookOpen01,
  Brush01,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronSelectorVertical,
  Circle,
  Clock,
  Copy01,
  CornerDownLeft,
  CornerDownRight,
  DotsHorizontal,
  DotsVertical,
  Dropper,
  Edit02,
  Folder,
  Globe01,
  Heart,
  Home01,
  Image01,
  Inbox01,
  InfoCircle,
  LayoutLeft,
  LayoutRight,
  Lightbulb02,
  Link01,
  Loading01,
  Lock01,
  Mail01,
  Menu01,
  MessageCircle01,
  Monitor01,
  Moon01,
  Palette,
  PauseCircle,
  Play,
  Plus,
  RefreshCcw01,
  Rocket01,
  Scale01,
  SearchMd,
  Settings01,
  Shield01,
  SkipForward,
  Sliders01,
  Square,
  Star01,
  Stars02,
  Sun,
  User01,
  Users01,
  XClose,
} from "@untitledui/icons";
import type { IconComponent, IconName } from "./icon-context.tsx";

export const untitledIcons: Record<IconName, IconComponent> = {
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "x": XClose,
  "copy": Copy01,
  "menu": Menu01,
  // No dot glyph: the plain circle.
  "dot": Circle,
  "monitor": Monitor01,
  "sun": Sun,
  "moon": Moon01,
  // No rectangle glyph: the square.
  "rectangle-horizontal": Square,
  "circle": Circle,
  // No library glyph: the open book.
  "square-library": BookOpen01,
  "clock": Clock,
  "star": Star01,
  "settings": Settings01,
  "plus": Plus,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "search": SearchMd,
  "loader": Loading01,
  "users": Users01,
  "lock": Lock01,
  "mail": Mail01,
  "bell": Bell01,
  "shield": Shield01,
  "palette": Palette,
  "lightbulb": Lightbulb02,
  "rocket": Rocket01,
  "heart": Heart,
  "paintbrush": Brush01,
  // No brain glyph: the sparkles Untitled UI uses for AI.
  "brain": Stars02,
  "globe": Globe01,
  "user": User01,
  "image": Image01,
  "link": Link01,
  "check": Check,
  "rotate-ccw": RefreshCcw01,
  "play": Play,
  // No bare pause glyph: the circled one.
  "pause": PauseCircle,
  "pipette": Dropper,
  "home": Home01,
  "message-circle": MessageCircle01,
  "inbox": Inbox01,
  "pencil": Edit02,
  "scaling": Scale01,
  "skip-forward": SkipForward,
  "corner-down-right": CornerDownRight,
  "corner-down-left": CornerDownLeft,
  "panel-left": LayoutLeft,
  "panel-right": LayoutRight,
  "chevrons-up-down": ChevronSelectorVertical,
  "more-horizontal": DotsHorizontal,
  "more-vertical": DotsVertical,
  "calendar": Calendar,
  "folder": Folder,
  "sliders-horizontal": Sliders01,
  "info": InfoCircle,
};
